[workspace]
members = [
    "src/rave",
    "src/rave_h264",
    "src/rave_h264_nvidia",
    "src/rave_mp4",
    "src/rave_ops",
    "src/rave_ops_nvidia",
    "src/rave_rtp",
    "src/rave_rtsp",
    "src/rave_sdp",
    "src/rave_types",
]
