[package]
name = "rave_rtsp"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1.4" }
http = "0.2"
tokio-util = { version = "0.7", default-features = false, features = ["codec"] }