[package]
name = "rave_rtsp"
version.workspace = true
edition.workspace = true

[dependencies]
base = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
tokio-util = { workspace = true }
